# -*- coding: utf-8 -*-
"""AppFinanciero.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jHTVGFmeRVzpFSpQwkzQsxgy8nkvdL2e
"""

# Proyecto: APP Financiero
# Desarrollado por: Alejandro Cañas, Emmanuel García, Maricielo Gómez
# Descripción: App que determina el perfil del inversor y analiza acciones con Python.

pip install streamlit yfinance

pip install streamlit-option-menu

# Importar librerias ----
import streamlit as st #Interfaz intercativo
import pandas as pd #Manejo de dataframes
import numpy as np #Soporte de cálculo matemáticos y matrices
import yfinance as yf #Datos financieros de Yahoo Finance
import matplotlib.pyplot as plt #Gráficos y visualizaciones de datos
import datetime #Manejo de fechas
from streamlit_option_menu import option_menu

# Inicializar variable de sesión ---
if "perfil" not in st.session_state:
    st.session_state.perfil = None

# Crear menú lateral
with st.sidebar:
    seleccion = option_menu(
        "APP Financiero",
        ["Inicio", "Perfil de inversor", "Simulación de portafolio - Una acción", "Simulación de portafolio - Dos o más acciones", "Referencias"],
        icons=["house", "graph-up", "bar-chart", "gear"],
        menu_icon="cast",
        default_index=0,
        orientation="vertical",
    )

# Contenido dinámico
if seleccion == "Inicio":
    st.title("🏠 Bienvenido al simulador financiero")

elif seleccion == "Simulación":
    st.header("📊 Simulación de portafolio")

elif seleccion == "Resultados":
    st.header("📈 Resultados del análisis")

elif seleccion == "Configuración":
    st.header("⚙️ Configuración de usuario")